version: '3.9'

services:
  app:
    build: .
    container_name: app
    volumes:
      - ./:/go/src/app
    ports:
      - '8080:8080'
    depends_on:
      - mysql

  db:
    image: mysql:5.7
    container_name: database
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
